ls:
  src/components:
    .dir: PascalCase | lowercase # lowercase allows `components/` folder naming itself
    .module.scss: PascalCase
    .props.tsx: PascalCase
    .tsx: PascalCase | lowercase # lowercase allows `index.ts{x}` files
  src/hooks:
    .dir: camelCase
    .tsx: camelCase | lowercase
  src/layouts:
    .dir: PascalCase | lowercase
    .module.scss: PascalCase
    .props.tsx: PascalCase
    .tsx: PascalCase | lowercase
  src/pages:
    .dir: kebab-case
    .tsx: kebab-case
  src/styles:
    .dir: kebab-case
    .module.scss: PascalCase
    .scss: kebab-case
  src/utils:
    .dir: camelCase
    .tsx: camelCase | lowercase

ignore:
  - src/pages/_app.tsx
